#server:
#  port: 8082

spring:
  application:
    name: zuulproxy

#eureka:
#  client:
#    registryFetchIntervalSeconds: 15
#    service-url: 
#      defaultZone: https://eureka-a1b2e5d9-a892-4afa-84b5-1c4997dcee84.apps.px-01.cf.t-mobile.com/eureka/
      
zuul:
  routes:
    readservice:
      path: /book/**
      stripPrefix: false
      serviceId: readingservice
    bookstore:
      path: /bookstore/**
      stripPrefix: false
      serviceId: bookstoreservice
          
ribbon:
  serverListRefreshInterval: 30000
  eureka:
    enabled: true
  ReadTimeout: 120000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1200000
